from gym.envs.mujoco.mujoco_env import MujocoEnv
# ^^^^^ so that user gets the correct error
# message if mujoco is not installed correctly
from gym.envs.mujoco.ant import AntEnv
from gym.envs.mujoco.half_cheetah import HalfCheetahEnv
from gym.envs.mujoco.hopper import HopperEnv
from gym.envs.mujoco.walker2d import Walker2dEnv
from gym.envs.mujoco.humanoid import HumanoidEnv
from gym.envs.mujoco.inverted_pendulum import InvertedPendulumEnv
from gym.envs.mujoco.inverted_double_pendulum import InvertedDoublePendulumEnv
from gym.envs.mujoco.reacher import ReacherEnv
from gym.envs.mujoco.swimmer import SwimmerEnv
from gym.envs.mujoco.humanoidstandup import HumanoidStandupEnv

from gym.envs.mujoco.pusher import PusherEnv
from gym.envs.mujoco.pusher1 import PusherEnv1
from gym.envs.mujoco.pusher2 import PusherEnv2
from gym.envs.mujoco.pusher3 import PusherEnv3
from gym.envs.mujoco.pusher4 import PusherEnv4
from gym.envs.mujoco.pusher5 import PusherEnv5
from gym.envs.mujoco.pusher6 import PusherEnv6
from gym.envs.mujoco.pusher7 import PusherEnv7
from gym.envs.mujoco.pusher8 import PusherEnv8
from gym.envs.mujoco.pusher9 import PusherEnv9
from gym.envs.mujoco.pusher10 import PusherEnv10
from gym.envs.mujoco.pusher11 import PusherEnv11
from gym.envs.mujoco.pusher12 import PusherEnv12
from gym.envs.mujoco.pusher13 import PusherEnv13
from gym.envs.mujoco.pusher14 import PusherEnv14
from gym.envs.mujoco.pusher15 import PusherEnv15
from gym.envs.mujoco.pusher16 import PusherEnv16
from gym.envs.mujoco.pusher17 import PusherEnv17
from gym.envs.mujoco.pusher18 import PusherEnv18
from gym.envs.mujoco.pusher19 import PusherEnv19
from gym.envs.mujoco.pusher20 import PusherEnv20
from gym.envs.mujoco.pusher21 import PusherEnv21
from gym.envs.mujoco.pusher22 import PusherEnv22
from gym.envs.mujoco.pusher23 import PusherEnv23
from gym.envs.mujoco.pusher24 import PusherEnv24
from gym.envs.mujoco.pusher25 import PusherEnv25
from gym.envs.mujoco.pusher26 import PusherEnv26
from gym.envs.mujoco.pusher27 import PusherEnv27
from gym.envs.mujoco.pusher28 import PusherEnv28
from gym.envs.mujoco.pusher29 import PusherEnv29
from gym.envs.mujoco.pusher30 import PusherEnv30
from gym.envs.mujoco.pusher31 import PusherEnv31
from gym.envs.mujoco.pusher32 import PusherEnv32
from gym.envs.mujoco.pusher33 import PusherEnv33
from gym.envs.mujoco.pusher34 import PusherEnv34
from gym.envs.mujoco.pusher35 import PusherEnv35
from gym.envs.mujoco.pusher36 import PusherEnv36
from gym.envs.mujoco.pusher37 import PusherEnv37
from gym.envs.mujoco.pusher38 import PusherEnv38
from gym.envs.mujoco.pusher39 import PusherEnv39
from gym.envs.mujoco.pusher40 import PusherEnv40
from gym.envs.mujoco.pusher41 import PusherEnv41
from gym.envs.mujoco.pusher42 import PusherEnv42
from gym.envs.mujoco.pusher43 import PusherEnv43
from gym.envs.mujoco.pusher44 import PusherEnv44
from gym.envs.mujoco.pusher45 import PusherEnv45
from gym.envs.mujoco.pusher46 import PusherEnv46
from gym.envs.mujoco.pusher47 import PusherEnv47
from gym.envs.mujoco.pusher48 import PusherEnv48
from gym.envs.mujoco.pusher49 import PusherEnv49
from gym.envs.mujoco.pusher50 import PusherEnv50
from gym.envs.mujoco.pusher51 import PusherEnv51
from gym.envs.mujoco.pusher52 import PusherEnv52
from gym.envs.mujoco.pusher53 import PusherEnv53
from gym.envs.mujoco.pusher54 import PusherEnv54
from gym.envs.mujoco.pusher55 import PusherEnv55
from gym.envs.mujoco.pusher56 import PusherEnv56
from gym.envs.mujoco.pusher57 import PusherEnv57
from gym.envs.mujoco.pusher58 import PusherEnv58
from gym.envs.mujoco.pusher59 import PusherEnv59
from gym.envs.mujoco.pusher60 import PusherEnv60
from gym.envs.mujoco.pusher61 import PusherEnv61
from gym.envs.mujoco.pusher62 import PusherEnv62
from gym.envs.mujoco.pusher63 import PusherEnv63
from gym.envs.mujoco.pusher64 import PusherEnv64
from gym.envs.mujoco.pusher65 import PusherEnv65
from gym.envs.mujoco.pusher66 import PusherEnv66
from gym.envs.mujoco.pusher67 import PusherEnv67
from gym.envs.mujoco.pusher68 import PusherEnv68
from gym.envs.mujoco.pusher69 import PusherEnv69
from gym.envs.mujoco.pusher70 import PusherEnv70
from gym.envs.mujoco.pusher71 import PusherEnv71
from gym.envs.mujoco.pusher72 import PusherEnv72
from gym.envs.mujoco.pusher73 import PusherEnv73
from gym.envs.mujoco.pusher74 import PusherEnv74
from gym.envs.mujoco.pusher75 import PusherEnv75
from gym.envs.mujoco.pusher76 import PusherEnv76
from gym.envs.mujoco.pusher77 import PusherEnv77
from gym.envs.mujoco.pusher78 import PusherEnv78
from gym.envs.mujoco.pusher79 import PusherEnv79
from gym.envs.mujoco.pusher80 import PusherEnv80
from gym.envs.mujoco.pusher81 import PusherEnv81
from gym.envs.mujoco.pusher82 import PusherEnv82
from gym.envs.mujoco.pusher83 import PusherEnv83
from gym.envs.mujoco.pusher84 import PusherEnv84
from gym.envs.mujoco.pusher85 import PusherEnv85
from gym.envs.mujoco.pusher86 import PusherEnv86
from gym.envs.mujoco.pusher87 import PusherEnv87
from gym.envs.mujoco.pusher88 import PusherEnv88
from gym.envs.mujoco.pusher89 import PusherEnv89
from gym.envs.mujoco.pusher90 import PusherEnv90
from gym.envs.mujoco.pusher91 import PusherEnv91
from gym.envs.mujoco.pusher92 import PusherEnv92
from gym.envs.mujoco.pusher93 import PusherEnv93
from gym.envs.mujoco.pusher94 import PusherEnv94
from gym.envs.mujoco.pusher95 import PusherEnv95
from gym.envs.mujoco.pusher96 import PusherEnv96
from gym.envs.mujoco.pusher97 import PusherEnv97
from gym.envs.mujoco.pusher98 import PusherEnv98
from gym.envs.mujoco.pusher99 import PusherEnv99
from gym.envs.mujoco.pusher100 import PusherEnv100
from gym.envs.mujoco.pusher101 import PusherEnv101
from gym.envs.mujoco.pusher102 import PusherEnv102
from gym.envs.mujoco.pusher103 import PusherEnv103
from gym.envs.mujoco.pusher104 import PusherEnv104
from gym.envs.mujoco.pusher105 import PusherEnv105
from gym.envs.mujoco.pusher106 import PusherEnv106
from gym.envs.mujoco.pusher107 import PusherEnv107
from gym.envs.mujoco.pusher108 import PusherEnv108
from gym.envs.mujoco.pusher109 import PusherEnv109
from gym.envs.mujoco.pusher110 import PusherEnv110
from gym.envs.mujoco.pusher111 import PusherEnv111
from gym.envs.mujoco.pusher112 import PusherEnv112
from gym.envs.mujoco.pusher113 import PusherEnv113
from gym.envs.mujoco.pusher114 import PusherEnv114
from gym.envs.mujoco.pusher115 import PusherEnv115
from gym.envs.mujoco.pusher116 import PusherEnv116
from gym.envs.mujoco.pusher117 import PusherEnv117
from gym.envs.mujoco.pusher118 import PusherEnv118
from gym.envs.mujoco.pusher119 import PusherEnv119
from gym.envs.mujoco.pusher120 import PusherEnv120
from gym.envs.mujoco.pusher121 import PusherEnv121
from gym.envs.mujoco.pusher122 import PusherEnv122
from gym.envs.mujoco.pusher123 import PusherEnv123
from gym.envs.mujoco.pusher124 import PusherEnv124
from gym.envs.mujoco.pusher125 import PusherEnv125
from gym.envs.mujoco.pusher126 import PusherEnv126
from gym.envs.mujoco.pusher127 import PusherEnv127
from gym.envs.mujoco.pusher128 import PusherEnv128
from gym.envs.mujoco.pusher129 import PusherEnv129
from gym.envs.mujoco.pusher130 import PusherEnv130
from gym.envs.mujoco.pusher131 import PusherEnv131
from gym.envs.mujoco.pusher132 import PusherEnv132
from gym.envs.mujoco.pusher133 import PusherEnv133
from gym.envs.mujoco.pusher134 import PusherEnv134
from gym.envs.mujoco.pusher135 import PusherEnv135
from gym.envs.mujoco.pusher136 import PusherEnv136
from gym.envs.mujoco.pusher137 import PusherEnv137
from gym.envs.mujoco.pusher138 import PusherEnv138
from gym.envs.mujoco.pusher139 import PusherEnv139

from gym.envs.mujoco.thrower import ThrowerEnv
from gym.envs.mujoco.thrower1 import ThrowerEnv1
from gym.envs.mujoco.thrower2 import ThrowerEnv2
from gym.envs.mujoco.thrower3 import ThrowerEnv3
from gym.envs.mujoco.thrower4 import ThrowerEnv4
from gym.envs.mujoco.thrower5 import ThrowerEnv5
from gym.envs.mujoco.thrower6 import ThrowerEnv6
from gym.envs.mujoco.thrower7 import ThrowerEnv7
from gym.envs.mujoco.thrower8 import ThrowerEnv8
from gym.envs.mujoco.thrower9 import ThrowerEnv9
from gym.envs.mujoco.thrower10 import ThrowerEnv10
from gym.envs.mujoco.thrower11 import ThrowerEnv11
from gym.envs.mujoco.thrower12 import ThrowerEnv12
from gym.envs.mujoco.thrower13 import ThrowerEnv13
from gym.envs.mujoco.thrower14 import ThrowerEnv14
from gym.envs.mujoco.thrower15 import ThrowerEnv15
from gym.envs.mujoco.thrower16 import ThrowerEnv16
from gym.envs.mujoco.thrower17 import ThrowerEnv17
from gym.envs.mujoco.thrower18 import ThrowerEnv18
from gym.envs.mujoco.thrower19 import ThrowerEnv19
from gym.envs.mujoco.thrower20 import ThrowerEnv20
from gym.envs.mujoco.thrower21 import ThrowerEnv21
from gym.envs.mujoco.thrower22 import ThrowerEnv22
from gym.envs.mujoco.thrower23 import ThrowerEnv23
from gym.envs.mujoco.thrower24 import ThrowerEnv24
from gym.envs.mujoco.thrower25 import ThrowerEnv25
from gym.envs.mujoco.thrower26 import ThrowerEnv26
from gym.envs.mujoco.thrower27 import ThrowerEnv27
from gym.envs.mujoco.thrower28 import ThrowerEnv28
from gym.envs.mujoco.thrower29 import ThrowerEnv29
from gym.envs.mujoco.thrower30 import ThrowerEnv30
from gym.envs.mujoco.thrower31 import ThrowerEnv31
from gym.envs.mujoco.thrower32 import ThrowerEnv32
from gym.envs.mujoco.thrower33 import ThrowerEnv33
from gym.envs.mujoco.thrower34 import ThrowerEnv34
from gym.envs.mujoco.thrower35 import ThrowerEnv35
from gym.envs.mujoco.thrower36 import ThrowerEnv36
from gym.envs.mujoco.thrower37 import ThrowerEnv37
from gym.envs.mujoco.thrower38 import ThrowerEnv38
from gym.envs.mujoco.thrower39 import ThrowerEnv39
from gym.envs.mujoco.thrower40 import ThrowerEnv40
from gym.envs.mujoco.thrower41 import ThrowerEnv41
from gym.envs.mujoco.thrower42 import ThrowerEnv42
from gym.envs.mujoco.thrower43 import ThrowerEnv43
from gym.envs.mujoco.thrower44 import ThrowerEnv44
from gym.envs.mujoco.thrower45 import ThrowerEnv45
from gym.envs.mujoco.thrower46 import ThrowerEnv46
from gym.envs.mujoco.thrower47 import ThrowerEnv47
from gym.envs.mujoco.thrower48 import ThrowerEnv48
from gym.envs.mujoco.thrower49 import ThrowerEnv49
from gym.envs.mujoco.thrower50 import ThrowerEnv50
from gym.envs.mujoco.thrower51 import ThrowerEnv51
from gym.envs.mujoco.thrower52 import ThrowerEnv52
from gym.envs.mujoco.thrower53 import ThrowerEnv53
from gym.envs.mujoco.thrower54 import ThrowerEnv54
from gym.envs.mujoco.thrower55 import ThrowerEnv55
from gym.envs.mujoco.thrower56 import ThrowerEnv56
from gym.envs.mujoco.thrower57 import ThrowerEnv57
from gym.envs.mujoco.thrower58 import ThrowerEnv58
from gym.envs.mujoco.thrower59 import ThrowerEnv59
from gym.envs.mujoco.thrower60 import ThrowerEnv60
from gym.envs.mujoco.thrower61 import ThrowerEnv61
from gym.envs.mujoco.thrower62 import ThrowerEnv62
from gym.envs.mujoco.thrower63 import ThrowerEnv63
from gym.envs.mujoco.thrower64 import ThrowerEnv64
from gym.envs.mujoco.thrower65 import ThrowerEnv65
from gym.envs.mujoco.thrower66 import ThrowerEnv66
from gym.envs.mujoco.thrower67 import ThrowerEnv67
from gym.envs.mujoco.thrower68 import ThrowerEnv68
from gym.envs.mujoco.thrower69 import ThrowerEnv69
from gym.envs.mujoco.thrower70 import ThrowerEnv70
from gym.envs.mujoco.thrower71 import ThrowerEnv71
from gym.envs.mujoco.thrower72 import ThrowerEnv72
from gym.envs.mujoco.thrower73 import ThrowerEnv73
from gym.envs.mujoco.thrower74 import ThrowerEnv74
from gym.envs.mujoco.thrower75 import ThrowerEnv75
from gym.envs.mujoco.thrower76 import ThrowerEnv76
from gym.envs.mujoco.thrower77 import ThrowerEnv77
from gym.envs.mujoco.thrower78 import ThrowerEnv78
from gym.envs.mujoco.thrower79 import ThrowerEnv79
from gym.envs.mujoco.thrower80 import ThrowerEnv80
from gym.envs.mujoco.thrower81 import ThrowerEnv81
from gym.envs.mujoco.thrower82 import ThrowerEnv82
from gym.envs.mujoco.thrower83 import ThrowerEnv83
from gym.envs.mujoco.thrower84 import ThrowerEnv84
from gym.envs.mujoco.thrower85 import ThrowerEnv85
from gym.envs.mujoco.thrower86 import ThrowerEnv86
from gym.envs.mujoco.thrower87 import ThrowerEnv87
from gym.envs.mujoco.thrower88 import ThrowerEnv88
from gym.envs.mujoco.thrower89 import ThrowerEnv89
from gym.envs.mujoco.thrower90 import ThrowerEnv90
from gym.envs.mujoco.thrower91 import ThrowerEnv91
from gym.envs.mujoco.thrower92 import ThrowerEnv92
from gym.envs.mujoco.thrower93 import ThrowerEnv93
from gym.envs.mujoco.thrower94 import ThrowerEnv94
from gym.envs.mujoco.thrower95 import ThrowerEnv95
from gym.envs.mujoco.thrower96 import ThrowerEnv96
from gym.envs.mujoco.thrower97 import ThrowerEnv97
from gym.envs.mujoco.thrower98 import ThrowerEnv98
from gym.envs.mujoco.thrower99 import ThrowerEnv99
from gym.envs.mujoco.thrower100 import ThrowerEnv100
from gym.envs.mujoco.thrower101 import ThrowerEnv101
from gym.envs.mujoco.thrower102 import ThrowerEnv102
from gym.envs.mujoco.thrower103 import ThrowerEnv103
from gym.envs.mujoco.thrower104 import ThrowerEnv104
from gym.envs.mujoco.thrower105 import ThrowerEnv105
from gym.envs.mujoco.thrower106 import ThrowerEnv106
from gym.envs.mujoco.thrower107 import ThrowerEnv107
from gym.envs.mujoco.thrower108 import ThrowerEnv108
from gym.envs.mujoco.thrower109 import ThrowerEnv109
from gym.envs.mujoco.thrower110 import ThrowerEnv110
from gym.envs.mujoco.thrower111 import ThrowerEnv111
from gym.envs.mujoco.thrower112 import ThrowerEnv112
from gym.envs.mujoco.thrower113 import ThrowerEnv113
from gym.envs.mujoco.thrower114 import ThrowerEnv114
from gym.envs.mujoco.thrower115 import ThrowerEnv115
from gym.envs.mujoco.thrower116 import ThrowerEnv116
from gym.envs.mujoco.thrower117 import ThrowerEnv117
from gym.envs.mujoco.thrower118 import ThrowerEnv118
from gym.envs.mujoco.thrower119 import ThrowerEnv119
from gym.envs.mujoco.thrower120 import ThrowerEnv120
from gym.envs.mujoco.thrower121 import ThrowerEnv121
from gym.envs.mujoco.thrower122 import ThrowerEnv122
from gym.envs.mujoco.thrower123 import ThrowerEnv123
from gym.envs.mujoco.thrower124 import ThrowerEnv124
from gym.envs.mujoco.thrower125 import ThrowerEnv125
from gym.envs.mujoco.thrower126 import ThrowerEnv126
from gym.envs.mujoco.thrower127 import ThrowerEnv127
from gym.envs.mujoco.thrower128 import ThrowerEnv128
from gym.envs.mujoco.thrower129 import ThrowerEnv129
from gym.envs.mujoco.thrower130 import ThrowerEnv130
from gym.envs.mujoco.thrower131 import ThrowerEnv131
from gym.envs.mujoco.thrower132 import ThrowerEnv132
from gym.envs.mujoco.thrower133 import ThrowerEnv133
from gym.envs.mujoco.thrower134 import ThrowerEnv134
from gym.envs.mujoco.thrower135 import ThrowerEnv135
from gym.envs.mujoco.thrower136 import ThrowerEnv136
from gym.envs.mujoco.thrower137 import ThrowerEnv137
from gym.envs.mujoco.thrower138 import ThrowerEnv138
from gym.envs.mujoco.thrower139 import ThrowerEnv139

from gym.envs.mujoco.striker import StrikerEnv
from gym.envs.mujoco.striker1 import StrikerEnv1
from gym.envs.mujoco.striker2 import StrikerEnv2
from gym.envs.mujoco.striker3 import StrikerEnv3
from gym.envs.mujoco.striker4 import StrikerEnv4
from gym.envs.mujoco.striker5 import StrikerEnv5
from gym.envs.mujoco.striker6 import StrikerEnv6
from gym.envs.mujoco.striker7 import StrikerEnv7
from gym.envs.mujoco.striker8 import StrikerEnv8
from gym.envs.mujoco.striker9 import StrikerEnv9
from gym.envs.mujoco.striker10 import StrikerEnv10
from gym.envs.mujoco.striker11 import StrikerEnv11
from gym.envs.mujoco.striker12 import StrikerEnv12
from gym.envs.mujoco.striker13 import StrikerEnv13
from gym.envs.mujoco.striker14 import StrikerEnv14
from gym.envs.mujoco.striker15 import StrikerEnv15
from gym.envs.mujoco.striker16 import StrikerEnv16
from gym.envs.mujoco.striker17 import StrikerEnv17
from gym.envs.mujoco.striker18 import StrikerEnv18
from gym.envs.mujoco.striker19 import StrikerEnv19
from gym.envs.mujoco.striker20 import StrikerEnv20
from gym.envs.mujoco.striker21 import StrikerEnv21
from gym.envs.mujoco.striker22 import StrikerEnv22
from gym.envs.mujoco.striker23 import StrikerEnv23
from gym.envs.mujoco.striker24 import StrikerEnv24
from gym.envs.mujoco.striker25 import StrikerEnv25
from gym.envs.mujoco.striker26 import StrikerEnv26
from gym.envs.mujoco.striker27 import StrikerEnv27
from gym.envs.mujoco.striker28 import StrikerEnv28
from gym.envs.mujoco.striker29 import StrikerEnv29
from gym.envs.mujoco.striker30 import StrikerEnv30
from gym.envs.mujoco.striker31 import StrikerEnv31
from gym.envs.mujoco.striker32 import StrikerEnv32
from gym.envs.mujoco.striker33 import StrikerEnv33
from gym.envs.mujoco.striker34 import StrikerEnv34
from gym.envs.mujoco.striker35 import StrikerEnv35
from gym.envs.mujoco.striker36 import StrikerEnv36
from gym.envs.mujoco.striker37 import StrikerEnv37
from gym.envs.mujoco.striker38 import StrikerEnv38
from gym.envs.mujoco.striker39 import StrikerEnv39
from gym.envs.mujoco.striker40 import StrikerEnv40
from gym.envs.mujoco.striker41 import StrikerEnv41
from gym.envs.mujoco.striker42 import StrikerEnv42
from gym.envs.mujoco.striker43 import StrikerEnv43
from gym.envs.mujoco.striker44 import StrikerEnv44
from gym.envs.mujoco.striker45 import StrikerEnv45
from gym.envs.mujoco.striker46 import StrikerEnv46
from gym.envs.mujoco.striker47 import StrikerEnv47
from gym.envs.mujoco.striker48 import StrikerEnv48
from gym.envs.mujoco.striker49 import StrikerEnv49
from gym.envs.mujoco.striker50 import StrikerEnv50
from gym.envs.mujoco.striker51 import StrikerEnv51
from gym.envs.mujoco.striker52 import StrikerEnv52
from gym.envs.mujoco.striker53 import StrikerEnv53
from gym.envs.mujoco.striker54 import StrikerEnv54
from gym.envs.mujoco.striker55 import StrikerEnv55
from gym.envs.mujoco.striker56 import StrikerEnv56
from gym.envs.mujoco.striker57 import StrikerEnv57
from gym.envs.mujoco.striker58 import StrikerEnv58
from gym.envs.mujoco.striker59 import StrikerEnv59
from gym.envs.mujoco.striker60 import StrikerEnv60
from gym.envs.mujoco.striker61 import StrikerEnv61
from gym.envs.mujoco.striker62 import StrikerEnv62
from gym.envs.mujoco.striker63 import StrikerEnv63
from gym.envs.mujoco.striker64 import StrikerEnv64
from gym.envs.mujoco.striker65 import StrikerEnv65
from gym.envs.mujoco.striker66 import StrikerEnv66
from gym.envs.mujoco.striker67 import StrikerEnv67
from gym.envs.mujoco.striker68 import StrikerEnv68
from gym.envs.mujoco.striker69 import StrikerEnv69
from gym.envs.mujoco.striker70 import StrikerEnv70
from gym.envs.mujoco.striker71 import StrikerEnv71
from gym.envs.mujoco.striker72 import StrikerEnv72
from gym.envs.mujoco.striker73 import StrikerEnv73
from gym.envs.mujoco.striker74 import StrikerEnv74
from gym.envs.mujoco.striker75 import StrikerEnv75
from gym.envs.mujoco.striker76 import StrikerEnv76
from gym.envs.mujoco.striker77 import StrikerEnv77
from gym.envs.mujoco.striker78 import StrikerEnv78
from gym.envs.mujoco.striker79 import StrikerEnv79
from gym.envs.mujoco.striker80 import StrikerEnv80
from gym.envs.mujoco.striker81 import StrikerEnv81
from gym.envs.mujoco.striker82 import StrikerEnv82
from gym.envs.mujoco.striker83 import StrikerEnv83
from gym.envs.mujoco.striker84 import StrikerEnv84
from gym.envs.mujoco.striker85 import StrikerEnv85
from gym.envs.mujoco.striker86 import StrikerEnv86
from gym.envs.mujoco.striker87 import StrikerEnv87
from gym.envs.mujoco.striker88 import StrikerEnv88
from gym.envs.mujoco.striker89 import StrikerEnv89
from gym.envs.mujoco.striker90 import StrikerEnv90
from gym.envs.mujoco.striker91 import StrikerEnv91
from gym.envs.mujoco.striker92 import StrikerEnv92
from gym.envs.mujoco.striker93 import StrikerEnv93
from gym.envs.mujoco.striker94 import StrikerEnv94
from gym.envs.mujoco.striker95 import StrikerEnv95
from gym.envs.mujoco.striker96 import StrikerEnv96
from gym.envs.mujoco.striker97 import StrikerEnv97
from gym.envs.mujoco.striker98 import StrikerEnv98
from gym.envs.mujoco.striker99 import StrikerEnv99
from gym.envs.mujoco.striker100 import StrikerEnv100
from gym.envs.mujoco.striker101 import StrikerEnv101
from gym.envs.mujoco.striker102 import StrikerEnv102
from gym.envs.mujoco.striker103 import StrikerEnv103
from gym.envs.mujoco.striker104 import StrikerEnv104
from gym.envs.mujoco.striker105 import StrikerEnv105
from gym.envs.mujoco.striker106 import StrikerEnv106
from gym.envs.mujoco.striker107 import StrikerEnv107
from gym.envs.mujoco.striker108 import StrikerEnv108
from gym.envs.mujoco.striker109 import StrikerEnv109
from gym.envs.mujoco.striker110 import StrikerEnv110
from gym.envs.mujoco.striker111 import StrikerEnv111
from gym.envs.mujoco.striker112 import StrikerEnv112
from gym.envs.mujoco.striker113 import StrikerEnv113
from gym.envs.mujoco.striker114 import StrikerEnv114
from gym.envs.mujoco.striker115 import StrikerEnv115
from gym.envs.mujoco.striker116 import StrikerEnv116
from gym.envs.mujoco.striker117 import StrikerEnv117
from gym.envs.mujoco.striker118 import StrikerEnv118
from gym.envs.mujoco.striker119 import StrikerEnv119
from gym.envs.mujoco.striker120 import StrikerEnv120
from gym.envs.mujoco.striker121 import StrikerEnv121
from gym.envs.mujoco.striker122 import StrikerEnv122
from gym.envs.mujoco.striker123 import StrikerEnv123
from gym.envs.mujoco.striker124 import StrikerEnv124
from gym.envs.mujoco.striker125 import StrikerEnv125
from gym.envs.mujoco.striker126 import StrikerEnv126
from gym.envs.mujoco.striker127 import StrikerEnv127
from gym.envs.mujoco.striker128 import StrikerEnv128
from gym.envs.mujoco.striker129 import StrikerEnv129
from gym.envs.mujoco.striker130 import StrikerEnv130
from gym.envs.mujoco.striker131 import StrikerEnv131
from gym.envs.mujoco.striker132 import StrikerEnv132
from gym.envs.mujoco.striker133 import StrikerEnv133
from gym.envs.mujoco.striker134 import StrikerEnv134
from gym.envs.mujoco.striker135 import StrikerEnv135
from gym.envs.mujoco.striker136 import StrikerEnv136
from gym.envs.mujoco.striker137 import StrikerEnv137
from gym.envs.mujoco.striker138 import StrikerEnv138
from gym.envs.mujoco.striker139 import StrikerEnv139
